import Head from "next/head";
import React from "react";

interface PageHeadProps {
  title?: string;
}

function PageHead({ title = "Software Engineer" }: PageHeadProps) {
  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <title>Yadab Sutradhar | {title}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
      <meta
        name="description"
        content="Website for Yadab Sutradhar, a software engineer with 4 years professional experience. Skilled with React, Next.js, JavaScript, TypeScript, AngularJs, VueJs, TailwindCSS, Sass, Node.js."
      ></meta>
      <meta property="og:url" content="https://yadab.me/" />
      <meta property="og:type" content="portfolio" />
      <meta property="og:locale" content="en" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default PageHead;
